### ISSUE TITLE
Design of AppendHandler

### ISSUE THREAD

**Issue by avgeorge** [veqryn/slog-dedup#1]
The append handler seems like it would be an issue to use with automation. Any system that ingests logs would have to handle values of `T` or `[]T` (actually `[]any`). The only advantage of the append handler seems to be that a human can view all the values that were logged with that key. But the increment handler allows the same, in slightly worse format, but without the disadvantage to automation. Is there a use case were the `AppendHandler` would be preferable?

If you want to group the extra values it might be better to combine it with the ignore/overwrite handler, so that one value gets used on the key and the rest get grouped like the current append handler.
e.g.
`OverwriteAndGroupExtra` (use the last value, group old values) can output
```json
{
    "time": "2023-10-03T01:45:00Z",
    "level": "INFO",
    "msg": "OverwriteAndGroupExtra handler",
    "duplicated": "two",
    "duplicated#extra": [
        "zero",
        "one"
    ]
}
```

`IgnoreAndGroupExtra` (use the first value, group any newer values) can output
```json
{
    "time": "2023-10-03T01:45:00Z",
    "level": "INFO",
    "msg": "IgnoreAndGroupExtra handler",
    "duplicated": "zero",
    "duplicated#extra": [
        "one",
        "two"
    ]
}
```

Though I'm not sure if it's worth it, seems like just using the increment handler gets you most of the same advantages.

**Comment by veqryn** [comment]
Hi, and thanks for looking at my repo and commenting!

I guess this particular question depends mostly on what is being done with the automation, and what the people/repo that are doing the logging expect.

Everyone using the repo wants to guarantee that the JSON logs being written are valid and have no duplicate keys _(*while the json spec is ambiguous and says that duplicates are undefined behavior, most real-world tools consider it invalid)_.  

But beyond that, the way I see it, there are 2 main ways to use this repo:
1. You aren't purposefully duplicating keys yourself in your own code/repos, but you are still concerned that it is a possibility it may happen by accident or by a library you are using.  You just want valid json and also want to see if duplicate keys ever happens, so you can go back and fix your code to not create them.  **Your use case mostly matches up with the IncrementHandler or the AppendHandler.**  I would probably prefer the IncrementHandler in this use case.
2. You are creating duplicate keys yourself on purpose, or your code is structured in a way that makes it inevitable _(ie: lots of different ways to enter a function that adds attributes to the logs, and some of those attributes may have already been added upstream)_.  The duplicated keys contain information about the same thing, and the values are either identical or the earlier/later attribute is just a more detailed version of the same thing.  **Your use case matches up with the OverwriteHandler _(this is my use personal case)_ or the IgnoreHandler.**

If we were to kind of combine these use cases, you could end up with what you describe: wanting a singular value for the first/last instance, and the rest of the attributes combined (or using the IncrementHandler, but with the order reversed).

The only issue with that, is that I'm not so sure that is a real use case.

**Do you want to give the repo a try, and report back on if you think this is a real use case?**
I am certainly open to adding it as a use case, and creating a new handler for it.

**Comment by veqryn** [comment]
Closed until more activity...
